# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-01 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(max_length=300)),
                ('p2', models.CharField(max_length=300)),
                ('p3', models.CharField(max_length=300)),
                ('p4', models.CharField(max_length=300)),
            ],
        ),
    ]
