# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-03 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='cmobile',
            field=models.IntegerField(null=True),
        ),
    ]
