# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-06 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('events', '0002_coordinator_cmobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=30, null=True)),
                ('events_name', models.CharField(blank=True, max_length=30, null=True)),
                ('member2', models.CharField(blank=True, max_length=50, null=True)),
                ('member3', models.CharField(blank=True, max_length=50, null=True)),
                ('member4', models.CharField(blank=True, max_length=50, null=True)),
                ('member5', models.CharField(blank=True, max_length=50, null=True)),
                ('events', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Events')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
    ]
