# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-07 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180808_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='imgid',
            field=models.CharField(max_length=4),
        ),
    ]
